#%RAML 1.0
title: customer-sapi
traits:
  client-id-requried:
    headers:
      client_id:
        type: string
        required: true
      client_secret:
        type: string
        required: true
/system_raml:
  get:
    is:
      - client-id-requried
    responses:
      200:
        body:
          application/json:
            example: !include getresponse.json
              